### ISSUE TITLE
Animation in TableView not showing while scrolling

### ISSUE THREAD

**Issue by beseder42** [kirualex/KAProgressLabel#32] opened 2016-02-13 14:04 UTC
If the ProgressLabel is used in a TableView Cell it will not update its animation while scrolling. To support updates during scrolling the NSTimer for the animation needs to run in `NSRunLoopCommonModes`:

This needs to be changed in TPPropertyAnimation.m:

`- (void)addAnimation:(TPPropertyAnimation *)animation {
    
    if ( !animations ) {
        animations = [[NSMutableArray alloc] init];
    }
    
    [animations addObject:animation];
    
    if ( !timer ) {
        if ( NSClassFromString(@"CADisplayLink") != NULL ) {
            timer = [CADisplayLink displayLinkWithTarget:self selector:@selector(update:)];
            [timer addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
        } else {
            timer = [NSTimer scheduledTimerWithTimeInterval:kRefreshRate target:self selector:@selector(update:) userInfo:nil repeats:YES];
        }
    }
}`

This should probably not be standard implementation, but in case someone needs it, it should be documented somewhere.

**Comment by ipedro** [comment] 2016-06-20 21:56
Just ran across this, and was about to submit a PR with that same change.
What's the downside of using it as a the standard implementation @beseder42 ?

**Comment by kirualex** [comment] 2016-06-22 23:22
Duplicate of #25, moving the conversation there

**Closed by kirualex** 2016-06-22 23:22 UTC
Labels: duplicate
